---
output: 
  html_document:
      css: styles.css
runtime: shiny
---
  
# Evaluation of OC MS4 monitoring program, dry weather monitoring {.tabset}
  
```{r setup, message = F, warning = F, results = 'hide', echo = F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = F, fig.path = 'figs/', dev.args = list(family = 'serif'))

library(tidyverse)
library(sf)
library(mapview)
library(lubridate)
library(leafsync)
library(viridisLite)
library(lubridate)
library(gridExtra)
library(stargazer)
library(EnvStats)
library(shiny)
library(kableExtra)
library(mgcv)
library(metR)
library(shinyWidgets)

mptyps <- c("CartoDB.Positron", "CartoDB.DarkMatter", "OpenStreetMap", "Esri.WorldImagery", "OpenTopoMap")

mapviewOptions(leafletHeight = 300)

prj <- 4326 # wgs84

source('R/funcs.R')

thm1 <- theme_bw(base_size = 16) + 
  theme(
    strip.background = element_blank(), 
    strip.placement = 'outside', 
    axis.title.x = element_blank(), 
    legend.title = element_blank(), 
    legend.position = 'bottom', 
    panel.grid = element_blank()
  )

thm2 <- theme_bw(base_size = 16) + 
  theme(
    strip.background = element_blank(), 
    strip.placement = 'outside', 
    legend.position = 'bottom', 
    panel.grid = element_blank()
  )

data(dwdat)

# rename some nutrient parameters
dwdat <- dwdat %>% 
  mutate(
    Parameter = case_when(
      Parameter %in% c('AmmoniaN', 'AmmoniaAsN') ~ 'Ammonia', 
      Parameter %in% 'NitrateNitriteNO3' ~ 'Nitrate, Nitrite', 
      Parameter %in% 'TKN' ~ 'Total Kjeldahl Nitrogen',
      Parameter %in% 'NitrateAsN' ~ 'Total Nitrogen',
      Parameter %in% 'OrthoPhosphateP' ~ 'Orthophosphate', 
      Parameter %in% 'TotalPhosphorusPO4' ~ 'Total Phosphorus', 
      T ~ Parameter
    )
  ) 

# nutrientd and top ten parameters
nuts <- c('Ammonia', 'Nitrate, Nitrite', 'Total Kjeldahl Nitrogen', 'Total Nitrogen', 'Orthophosphate', 'Total Phosphorus')
tops <- table(dwdat$Parameter) %>% sort %>% rev %>% .[1:10] %>% names %>% sort
```

```{r reactives}
wshpardat <- reactive({

  # inputs
  wshsel <- input$wshsel
  varsel <- input$varsel

  out <- dwdat %>%
    filter(Watershed %in% wshsel) %>%
    mutate(
      Year = year(Date),
      Month = month(Date, label = T)
    ) %>%
    filter(Parameter %in% varsel)

  return(out)

})

# further subset of wshpardat by stations
stawshpardat <- reactive({
  
  # inputs
  wshpardat <- wshpardat()
  stasel <- input$stasel

  out <- wshpardat %>% 
    filter(StationCode %in% stasel)
  
  return(out)
  
})

# first observed plot
obsp1 <- reactive({

  req(nrow(stawshpardat()) > 0)
  
  # inputs
  stawshpardat <- stawshpardat()
  wshsel <- input$wshsel
  logsel <- input$logsel

  toplo <- stawshpardat
  
  # labels
  ylb <- paste0('Concentration (', unique(toplo$Units), ')')
  ttl <- unique(toplo$Parameter)

  p <- ggplot(toplo, aes(x = Date, y = Result, group = StationCode)) +
    geom_line() +
    geom_point() +
    thm1 +
    labs(
      subtitle = wshsel,
      title = ttl,
      y = ylb
    )
  
  if(logsel)
    p <- p + 
      scale_y_log10()

  return(p)

})

# second observed plot
obsp2 <- reactive({

  req(nrow(stawshpardat()) > 0)
  
  # inputs
  stawshpardat <- stawshpardat()
  wshsel <- input$wshsel
  logsel <- input$logsel

  toplo <- stawshpardat
  
  # labels
  ttl <- paste(unique(toplo$Parameter), 'by year')
  ylb <- paste0('Concentration (', unique(toplo$Units), ')')

  p <- ggplot(toplo, aes(x = factor(Year), y = Result, group = Year)) +
    geom_boxplot() +
    facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
    thm1 +
    labs(
      subtitle = wshsel,
      title = ttl,
      y = ylb
    )
  
  if(logsel)
    p <- p + 
      scale_y_log10()

  return(p)

})

# third observed plot
obsp3 <- reactive({

  req(nrow(stawshpardat()) > 0)
  
  # inputs
  stawshpardat <- stawshpardat()
  wshsel <- input$wshsel
  logsel <- input$logsel
  
  toplo <- stawshpardat
  
  # labels
  ttl <- paste(unique(toplo$Parameter), 'by month')
  ylb <- paste0('Concentration (', unique(toplo$Units), ')')
  
  p <- ggplot(toplo, aes(x = Month, y = Result, group = Month)) +
    geom_boxplot() +
    facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
    thm1 +
    labs(
      subtitle = wshsel,
      title = ttl,
      y = ylb
    )

  if(logsel)
    p <- p + 
      scale_y_log10()
  
  return(p)

})

# # trend data
# trnddat <- reactive({
# 
#   # input
#   wshpardat <- wshpardat()
# 
#   out <- wshpardat %>%
#     group_by(Parameter, Year) %>%
#     summarise(
#       confint = t.test(Result)$conf.int %>% range %>% diff,
#       confint = confint / 2,
#       Result = mean(Result, na.rm = T),
#     ) %>%
#     group_by(Parameter) %>%
#     mutate(
#       avg = mean(Result, na.rm = T),
#       dev = Result - avg
#     ) %>%
#     ungroup %>%
#     mutate(
#       avg = round(avg, 2),
#       Parameter = paste0(Parameter, ' (', avg, ')')
#     )
# 
#   return(out)
# 
# })
# 
# # first trend plot
# trndp1 <- reactive({
# 
#   # input
#   trnddat <- trnddat()
#   wshsel <- input$wshsel
# 
#   subttl <- paste0(wshsel, ', average in parentheses on y-axis')
# 
#   p <- ggplot(trnddat, aes(x = Year, y = dev, fill = dev)) +
#     geom_bar(stat = 'identity', colour = 'grey') +
#     # geom_errorbar(aes(ymin = dev - confint, ymax = dev + confint), width = 0) +
#     scale_fill_gradient2('Deviations from average (+/-)', low = 'tomato1', mid = 'grey90', high = 'lightgreen', midpoint = 0) +
#     facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
#     thm1 +
#     geom_smooth(method = 'lm', se = F, linetype = 'dashed', color = 'black') +
#     # scale_y_log10() +
#     # scale_y_continuous('Density (fish/100ft)') +
#     geom_hline(aes(yintercept = 0)) +
#     labs(
#       title = 'Deviation from annual averages by constituent (mg/L)',
#       subtitle = subttl
#     ) +
#     guides(fill = guide_colourbar(barwidth = 15, barheight = 0.5))
# 
#   return(p)
# 
# })
# 
# # first trend table
# trndtab1 <- reactive({
# 
#   # input
#   trnddat <- trnddat()
# 
#   mods <- trnddat %>%
#     group_by(Parameter) %>%
#     nest %>%
#     mutate(
#       mod = purrr::map(data, function(x) lm(dev ~ Year, x))
#     ) %>%
#     ungroup %>%
#     mutate(
#       Parameter = gsub('\\s\\(.*\\)$', '', Parameter)
#     )
# 
#   out <- stargazer(mods$mod, type = 'html',
#                    covariate.labels = c('Year', 'Intercept'),
#                    column.labels = mods$Parameter,
#                    omit.stat = c('adj.rsq', 'ser'),
#                    column.sep.width = '10pt',
#                    dep.var.labels.include = F,
#                    digits = 2
#   ) %>%
#     HTML()
# 
#   return(out)
# 
# })
# 
# # second trend plot
# trndp2 <- reactive({
# 
#   # input
#   wshpardat <- wshpardat()
#   wshsel <- input$wshsel
#   varsel <- input$varsel
# 
#   win <- 12
#   toplo <- wshpardat %>%
#     select(Date, Parameter, Result) %>%
#     mutate(Date = floor_date(Date, unit = 'month')) %>%
#     group_by(Date, Parameter) %>%
#     summarise(Result = mean(Result, na.rm = T)) %>%
#     # group_by(Parameter) %>%
#     arrange(Parameter, Date) %>%
#     group_by(Parameter) %>%
#     mutate(
#       avg = stats::filter(Result, rep(1, win)/win, sides = 1, method = 'convolution')
#     ) %>%
#     ungroup %>%
#     mutate(
#       dev = Result - avg
#     )
# 
#   p1 <- ggplot(toplo, aes(x = Date, y = Result)) +
#     geom_line() +
#     facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
#     thm1 +
#     # scale_y_log10() +
#     labs(
#       title = paste0('Observed ', varsel),
#       subtitle = wshsel,
#       ylab = 'Concentration (mg/L)'
#     )
# 
#   p2 <- ggplot(toplo, aes(x = Date, y = avg)) +
#     geom_segment(aes(x = Date, xend = Date, yend = avg, y = avg + dev, colour = dev), size = 0.8) +
#     geom_line(colour = 'black') +
#     facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
#     thm1 +
#     theme(legend.position = 'right') +
#     # scale_y_log10() +
#     scale_colour_gradient2('Devation from average (+/-)', low = 'tomato1', mid = 'grey90', high = 'lightgreen', midpoint = 0) +
#     labs(
#       title = 'Deviations from annual average',
#       subtitle = wshsel,
#       ylab = NULL
#     )
# 
#   grid.arrange(
#     arrangeGrob(p1, p2, ncol = 2, widths = c(0.8,1))
#   )
# 
# })
# 
# # second trends table
# trndtab2 <- reactive({
# 
#   # input
#   wshpardat <- wshpardat()
# 
#   totabs1kn <- wshpardat %>%
#     group_by(Parameter, Year) %>%
#     summarise(
#       Result = mean(Result, na.rm = T),
#     ) %>%
#     group_by(Parameter) %>%
#     mutate(
#       avg = mean(Result, na.rm = T),
#       dev = Result - avg
#     ) %>%
#     nest %>%
#     mutate(
#       res = purrr::map(data, function(x){
# 
#         knout <- kendallTrendTest(dev ~ Year, x)
#         outest <- round(knout$estimate, 2)
#         outpval <- p_ast(knout$p.value)
#         nval <- nrow(na.omit(x))
#         out <- c(n = nval, outest, pval = outpval) %>%
#           data.frame %>%
#           t %>%
#           data.frame %>%
#           select(-intercept)
#         return(out)
# 
#       })
# 
#     ) %>%
#     select(-data) %>%
#     unnest(res)
# 
#   out <- HTML(knitr::kable(totabs1kn, format = 'html') %>%
#                 kable_styling(full_width = T, font_size = 14))
# 
#   return(out)
# 
# })
# 
# # power analysis data
# powdat <- reactive({
# 
#   # input
#   wshsel <- input$wshsel
#   varsel <- input$varsel
# 
#   out <- medat %>%
#     filter(StationCode %in% wshsel) %>%
#     mutate(
#       Parameter = case_when(
#         Parameter %in% 'AmmoniaN' ~ 'Ammonia',
#         Parameter %in% 'NitrateNitriteNO3' ~ 'Nitrate, Nitrite',
#         Parameter %in% 'TKN' ~ 'Total Kjeldahl Nitrogen',
#         Parameter %in% 'OrthoPhosphateP' ~ 'Orthophosphate',
#         Parameter %in% 'TotalPhosphorusPO4' ~ 'Total Phosphorus',
#         T ~ Parameter
#       ),
#       Year = year(Date),
#       Season = yday(Date),
#       dectime = decimal_date(Date)
#     ) %>%
#     filter(Parameter %in% varsel)
# 
#   return(out)
# 
# })
# 
# # first power analysis plot
# powplo1 <- reactive({
# 
#   # input
#   wshsel <- input$wshsel
#   varsel <- input$varsel
#   powdat <- powdat()
# 
#   p <- ggplot(powdat, aes(x = Date, y = Result)) +
#     geom_line() +
#     thm2 +
#     scale_y_log10() +
#     labs(
#       title = 'Observed time series',
#       subtitle = wshsel,
#       xlab = NULL,
#       ylab = paste0(varsel, ' (mg/L)')
#     )
# 
#   return(p)
# 
# })
# 
# # second power plot
# powplo2 <- reactive({
# 
#   # input
#   powdat <- powdat()
#   wshsel <- input$wshsel
#   varsel <- input$varsel
# 
#   scns <- crossing(
#     chg = seq(0.3, 1, length = 2),
#     eff = seq(0.3, 1, length = 2)
#   ) %>%
#     group_by(chg, eff) %>%
#     mutate(
#       simdat = purrr::pmap(list(chg, eff), ~simvals(powdat, chg, eff, sims = 20)),
#       sigs = purrr::map(simdat, function(x){
# 
#         x <- x %>%
#           group_by(sims) %>%
#           nest %>%
#           mutate(
#             pval = purrr::map(data, function(x){
# 
#               mod <- lm(simrand ~ dectime, data = x) %>% summary %>% .$fstatistic
#               pf(mod[1], mod[2], mod[3], lower.tail = F)
# 
#             }),
#             sig = case_when(
#               pval < 0.05 ~ 'sig',
#               pval >= 0.05 ~ 'nonsig'
#             )
#           ) %>%
#           ungroup %>%
#           select(sims, sig)
# 
#         return(x)
# 
#       })
#     )
# 
#   simdat <- scns %>%
#     select(-sigs) %>%
#     unnest(simdat)
# 
#   sigs <- scns %>%
#     select(-simdat) %>%
#     unnest(sigs)
# 
#   toplo <- simdat %>%
#     left_join(sigs, by = c('chg', 'eff', 'sims')) %>%
#     group_by(chg, eff) %>%
#     nest %>%
#     mutate(
#       pow = purrr::map(data, powfun)
#     ) %>%
#     unnest(c(data, pow)) %>%
#     ungroup %>%
#     mutate(
#       chg = paste('change', chg),
#       eff = paste('effort', eff),
#       pow = paste('power', pow),
#       sig = case_when(
#         sig == 'nonsig' ~ 'Non-significant',
#         sig == 'sig' ~ 'Significant'
#       )
#     ) %>%
#     unite('grp', chg, eff, pow, sep = ', ')
# 
#   p <- ggplot(toplo, aes(x = Date, y = exp(simrand), group = sims, col = sig)) +
#     geom_point(size = 0.2) +
#     geom_line(alpha = 0.2) +
#     facet_wrap(~ grp, ncol = 2) +
#     thm2 +
#     scale_y_log10() +
#     scale_colour_manual('', values = c('black', 'tomato1')) +
#     labs(
#       title = 'Observed time series (mg/L)',
#       subtitle = paste0(wshsel, ', twenty simulations per scenario'),
#       ylab = paste0('log-simulated ', varsel, ' (mg/L)'),
#       xlab = NULL
#     )
# 
#   return(p)
# 
# })
# 
# # third power plot
# powplo3 <- reactive({
# 
#   # input
#   wshsel <- input$wshsel
#   varsel <- input$varsel
# 
#   toplo <- pows %>%
#     filter(sta %in% wshsel) %>%
#     filter(par %in% varsel)
# 
#   p <- ggplot(toplo, aes(x = eff, y = chg, z = pow)) +
#     # geom_tile() +
#     geom_contour(aes(colour = stat(level))) +
#     scale_colour_viridis_c('Power') +
#     thm2 +
#     theme(legend.position = 'none') +
#     # scale_x_continuous(limits = c(0, 1)) +
#     # scale_y_continuous(limits = c(0, 1)) +
#     geom_text_contour() +
#     labs(
#       y = paste0('Magnitude of trend change (%) of ', varsel),
#       title = paste0('Power estimates for ', wshsel),
#       subtitle = 'Lines show power for varying sample effort and trend magnitude',
#       x = 'Relative sample effort'
#     )
# 
#   p
# 
# })
# 
# # fourth power plot
# powplo4 <- reactive({
# 
#   # inputs
#   powdat <- powdat()
#   wshsel <- input$wshsel
#   varsel <- input$varsel
# 
#   scns <- crossing(
#     thr = seq(1, 10, length = 2),
#     eff = seq(0.1, 1, length = 2)) %>%
#     group_by(thr, eff) %>%
#     mutate(
#       simdat = purrr::map(eff, ~thrvals(powdat, eff, sims = 20))
#     )
# 
#   toplo <- scns %>%
#     unnest(simdat) %>%
#     ungroup %>%
#     mutate(
#       thr = paste('exceedance', thr),
#       eff = paste('effort', eff)
#     ) %>%
#     unite('grp', thr, eff, sep = ', ', remove = F) %>%
#     mutate(
#       thr = gsub('^exceedance\\s', '', thr) %>% as.numeric,
#       val = case_when(
#         exp(simrand) > thr ~ 'Value above',
#         exp(simrand) <= thr ~'Value below'
#       )
#     )
# 
#   p <- ggplot(toplo, aes(x = Date, y = exp(simrand), group = sims)) +
#     geom_line(alpha = 0.2) +
#     geom_point(size = 0.5, aes(shape = val, col = val)) +
#     geom_hline(aes(yintercept = thr), linetype = 'dashed') +
#     facet_wrap(~ grp, nrow = 2) +
#     thm2 +
#     scale_y_log10() +
#     scale_colour_manual(NULL, values = c('tomato1', 'black')) +
#     scale_shape_manual(NULL, values = c(24, 25)) +
#     labs(
#       title = 'Observed time series (mg/L)',
#       subtitle = paste0(wshsel, ', twenty simulations per scenario'),
#       ylab = paste0('log-simulated ', varsel, ' (mg/L)'),
#       xlab = NULL
#     )
# 
#   p
# 
# })
# 
# # fifth power plot
# powplo5 <- reactive({
# 
#   # inputs
#   powdat <- powdat()
#   wshsel <- input$wshsel
#   varsel <- input$varsel
# 
#   scns <- crossing(
#     thr = seq(1, 10, length = 2),
#     eff = seq(0.1, 1, length = 2)) %>%
#     group_by(thr, eff) %>%
#     mutate(
#       simdat = purrr::map(eff, ~thrvals(powdat, eff, sims = 20))
#     )
# 
#   toplo <- scns %>%
#     mutate(
#       yrspow = purrr::pmap(list(thr, simdat), function(thr, simdat) {
# 
#         out <- simdat %>%
#           mutate(simrand = exp(simrand)) %>%
#           group_by(Year) %>%
#           summarise(
#             aveval = mean(simrand),
#             minval = t.test(simrand)$conf.int[1],
#             maxval = t.test(simrand)$conf.int[2]
#           ) %>%
#           mutate(sig = case_when(
#             maxval > thr ~ 'detected',
#             maxval < thr ~ 'not detected'
#           )
#           )
# 
#         return(out)
# 
#       })
#     ) %>%
#     unnest(yrspow) %>%
#     ungroup %>%
#     mutate(
#       thr = paste('exceedance', thr),
#       eff = paste('effort', eff)
#     ) %>%
#     unite('grp', thr, eff, sep = ', ', remove = F) %>%
#     mutate(thr = gsub('^exceedance\\s', '', thr) %>%  as.numeric)
# 
#   p <- ggplot(toplo, aes(x = factor(Year), y = aveval)) +
#     geom_bar(stat = 'identity', aes(fill = sig)) +
#     geom_errorbar(aes(ymin = minval, ymax = maxval, color = sig), width = 0) +
#     geom_hline(aes(yintercept = thr), linetype = 'dashed') +
#     scale_colour_manual(NULL, values = c('tomato1', 'black')) +
#     scale_fill_manual(NULL, values = c('tomato1', 'black')) +
#     facet_wrap(~ grp, nrow = 2) +
#     thm2 +
#     labs(
#       title = 'Ability to detect exceedance by year',
#       subtitle = paste0(wshsel, ', twenty simulations per scenario'),
#       y = paste0(varsel, ' concentration (mg/L)'),
#       x = NULL
#     )
# 
#   return(p)
# 
# })
# 
# # sixth power plot
# powplo6 <- reactive({
# 
#   # input
#   wshsel <- input$wshsel
#   varsel <- input$varsel
# 
#   toplo <- thrs %>%
#     filter(StationCode %in% wshsel) %>%
#     filter(Parameter %in% varsel)
# 
#   p <- ggplot(toplo, aes(x = eff, y = thr, z = pow)) +
#     # geom_tile() +
#     geom_contour(aes(colour = stat(level))) +
#     scale_colour_viridis_c('Power') +
#     thm2 +
#     theme(legend.position = 'none') +
#     # scale_x_continuous(limits = c(0, 1)) +
#     # scale_y_continuous(limits = c(0, 1)) +
#     geom_text_contour() +
#     labs(
#       y = paste0('Magnitude of observations above\nthe median for ', varsel),
#       title = paste0('Power estimates for ', wshsel),
#       subtitle = 'Lines show power for varying sample effort and thresholds',
#       x = 'Relative sample effort'
#     )
# 
#   p
# 
# })
```

## Inventory {.tabset .tabset-pills}

### Maps

Watersheds monitored, number of parameters measured, and number of years monitored at each station. 

```{r}
tomap <- dwdat %>% 
  select(StationCode, Watershed, Longitude, Latitude) %>% 
  unique %>% 
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = prj)

m1a <- mapview(tomap, zcol = 'Watershed', layer.name = 'Watershed location', homebutton = F, map.types = mptyps)

tomap <- dwdat %>% 
  select(StationCode, Parameter, Longitude, Latitude) %>% 
  unique %>% 
  group_by(StationCode, Longitude, Latitude) %>% 
  summarise(n = n()) %>% 
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = prj)

m2a <- mapview(tomap, zcol = 'n', layer.name = 'Number of parameters', homebutton = F, col.regions = magma, map.types = mptyps)

tomap <- dwdat %>% 
  select(StationCode, yr = Date, Longitude, Latitude) %>% 
  mutate(yr = year(yr)) %>% 
  unique %>% 
  group_by(StationCode, Longitude, Latitude) %>% 
  summarise(n = n()) %>% 
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = prj)

m3a <- mapview(tomap, zcol = 'n', layer.name = 'Number of years', homebutton = F, col.regions = magma, map.types = mptyps)

leafsync::sync(m1a, m2a, m3a, ncol = 1) 
```

### Tables

```{r toptab}
sums <- dwdat %>% 
  filter(Parameter %in% tops) %>% 
  count(Parameter, Watershed) %>% 
  bind_rows(group_by(., Parameter) %>%
              summarise(n=sum(n)) %>%
              mutate(Watershed='Total')) %>%
  bind_rows(group_by(., Watershed) %>%
              summarise(n=sum(n)) %>%
              mutate(Parameter='Total')) %>%
  spread(Parameter,n,fill=0) %>% 
  select_at(c('Watershed', tops, 'Total'))

alltot <- sums %>% 
  filter(Watershed != 'Total')
coltot <- sums %>% 
  filter(Watershed == 'Total')

totab <- bind_rows(alltot, coltot)

HTML(knitr::kable(totab, format = 'html', caption = "Top ten parameters") %>% 
       kable_styling(full_width = T, font_size = 14))
```

```{r toptabyr}
sums <- dwdat %>% 
  mutate(Year = as.character(year(Date))) %>% 
  filter(Parameter %in% tops) %>% 
  count(Year, Watershed) %>% 
  bind_rows(group_by(., Year) %>%
              summarise(n = sum(n)) %>%
              mutate(Watershed = 'Total')) %>%
  bind_rows(group_by(., Watershed) %>%
              summarise(n=sum(n)) %>%
              mutate(Year = 'Total')) %>%
  spread(Year,n,fill=0)

alltot <- sums %>% 
  filter(Watershed != 'Total')
coltot <- sums %>% 
  filter(Watershed == 'Total')

totab <- bind_rows(alltot, coltot)

HTML(knitr::kable(totab, format = 'html', caption = "Top ten parameters by year") %>% 
       kable_styling(full_width = T, font_size = 14))
```

```{r nuttab}
sums <- dwdat %>% 
  filter(Parameter %in% nuts) %>% 
  count(Parameter, Watershed) %>% 
  bind_rows(group_by(., Parameter) %>%
              summarise(n=sum(n)) %>%
              mutate(Watershed='Total')) %>%
  bind_rows(group_by(., Watershed) %>%
              summarise(n=sum(n)) %>%
              mutate(Parameter='Total')) %>%
  spread(Parameter,n,fill=0) %>% 
  select_at(c('Watershed', nuts, 'Total'))

alltot <- sums %>% 
  filter(Watershed != 'Total')
coltot <- sums %>% 
  filter(Watershed == 'Total')

totab <- bind_rows(alltot, coltot)

HTML(knitr::kable(totab, format = 'html', caption = "Nutrients") %>% 
       kable_styling(full_width = T, font_size = 14))
```

```{r nuttabyr}
sums <- dwdat %>% 
  mutate(Year = as.character(year(Date))) %>% 
  filter(Parameter %in% nuts) %>% 
  count(Year, Watershed) %>% 
  bind_rows(group_by(., Year) %>%
              summarise(n = sum(n)) %>%
              mutate(Watershed = 'Total')) %>%
  bind_rows(group_by(., Watershed) %>%
              summarise(n=sum(n)) %>%
              mutate(Year = 'Total')) %>%
  spread(Year,n,fill=0)

alltot <- sums %>% 
  filter(Watershed != 'Total')
coltot <- sums %>% 
  filter(Watershed == 'Total')

totab <- bind_rows(alltot, coltot)

HTML(knitr::kable(totab, format = 'html', caption = "Nutrients by year") %>% 
       kable_styling(full_width = T, font_size = 14))
```

## Analyses by watershed {.tabset .tabset-pills}

```{r}
column(12, 
       column(4, 
              selectInput('wshsel', 'Select watershed:', choices = unique(dwdat$Watershed))
       ),
       column(4,
               selectInput('varsel', 'Select constituent:', choices = c(tops, nuts), selected = 'ENT')
       ), 
       column(4, 
              renderUI({
      
                # input
                spaflt <- wshpardat()
                stas <- unique(wshpardat()$StationCode)
                
                pickerInput(inputId = "stasel", label = 'Select stations:', choices = stas,
                  options = list(`actions-box` = TRUE, size = 20), selected = stas, multiple = TRUE)      
                
              })
        )
)
column(12, 
       column(4, 
              selectInput('logsel', 'Log scale?', choices = c(F, T))
       )
)
```

### Observed

Observed time series for major nitrogen constituents.

```{r}
renderPlot({obsp1()}, height = 300, width = 700)
renderPlot({obsp2()}, height = 300, width = 700)
renderPlot({obsp3()}, height = 300, width = 700)
```

<!-- ### Trends -->

<!-- ```{r} -->
<!-- renderPlot({trndp1()}, height = 350, width = 900) -->
<!-- ``` -->

<!-- This table shows the regression results from the above plot. -->

<!-- ```{r, results='asis'} -->
<!-- renderUI({trndtab1()}) -->
<!-- ``` -->

<!-- The plots below show the observed time series (left) with measurements averaged to year/month (left) and a moving window average for a 12 month period with deviations around the average (right). -->

<!-- ```{r} -->
<!-- renderPlot({trndp2()}, height = 350, width = 900) -->
<!-- ``` -->

<!-- Kendall tests also provide an indication of a trend by evaluating magnitude, direction, and significance of a change in density between the selected years. The test is a non-parametric equivalent to the regression analysis above. The value for tau ranges from -1 to 1 and provides a measure of trend direction. The slope is the estimated change per year in density and the p-value shows the significance of the test. -->

<!-- ```{r, results = 'asis'} -->
<!-- renderUI({trndtab2()}) -->
<!-- ``` -->

<!-- ### Power analyses -->

<!-- A power analysis was conducted to estimate the ability to detect a specific trend for a desired sampling frequency.  This analysis involved repeated simulations of time series with similar characteristics as the data observed at station SDMF05.  Generally, power is described as the likelihood of observing an actual trend given the magnitude of the trend and sampling frequency.  __For all scenarios, sampling frequency is expressed as a proportion of the observed effort, with sampling at 100% effort equal to site visits every ~14 days across the period of record.__  Power is expected to decrease with decreasing trend magnitudes and decreasing sampling frequency. -->

<!-- The observed time series for `r renderText({input$varsel})` at `r renderText({input$wshsel})` is shown below.  The power analyses are specific to the characteristics of the time series at this station. -->

<!-- ```{r} -->
<!-- renderPlot({powplo1()}, height = 350, width = 900) -->
<!-- ``` -->

<!-- This plot shows 100 simulated time series of nitrogen trends that are based on variance estimates from the observed time series.  Four types of simulations are shown.  In the top left, a trend of 10\% change from the original value is shown with a sampling effort of 10\% that of the original time series. In the top right, a trend of 10\% change from the original value is shown with a sampling effort of 100\% that of the original time series. In the bottom left, a trend of 90\% change from the original value is shown with a sampling effort of 10\% that of the original time series. In the bottom left, a trend of 90\% change from the original value is shown with a sampling effort of 10\% that of the original time series. Lines in red are significant ($\alpha$ = 0.05) based on results of a linear trend analysis.  The total power is based on the number of significant results for each scenario divided by the total number of simulations (n = 20 for each).  As such, increasing power is observed with stronger trends and higher sampling densities. -->

<!-- ```{r} -->
<!-- renderPlot({powplo2()}, height = 550, width = 900) -->
<!-- ``` -->

<!-- This plot shows a summary of power for several efforts and trends. Power is based on 1000 simulations for each scenario (differing from the example above). Power is low for very small trends regardless of sample effort, whereas power is generally high for larger trends until effort falls below 40-50% of actual. -->

<!-- ```{r} -->
<!-- renderPlot({powplo3()}, height =650, width = 900) -->
<!-- ``` -->

<!-- An alternative power analysis was conducted to identify the ability to observe an exceedance for a nitrogen concentration for a given sample density.  This provides an indication of how likely you are to detect a concentration above a value of interest within your sampling design.  Overall, ability to detect an exceedance decreases with less frequency sampling and higher exceedance values.  The plots below show examples using simulated time series from the observed data at SDMF05.  The top left shows the power of observing an exceedance of 1 mg/L at 10\% sample effort.  The top right shows the power of observing an exceedance of 10 mg/L at 100\% sample effort. The bottom left shows the power of observing an exceedance of 5 mg/L at 10\% sample effort. The bottom right shows the power of observing an exceedance of 5 mg/L at 100\% sample effort.  Observations above the threshold are shown in red. -->

<!-- ```{r} -->
<!-- renderPlot({powplo4()}, height = 550, width = 900) -->
<!-- ``` -->

<!-- This plot shows the uncertainty associated with the average esimated concentration within each year.  The estimates served as a proxy for power given the sample effort and exceedance threshold. -->

<!-- ```{r} -->
<!-- renderPlot({powplo5()}, height = 550, width = 900) -->
<!-- ``` -->

<!-- Finally, power to detect observations above a given threshold is summarized below across different levels of effort and thresholds. Power is based on 1000 simulations for each scenario (differing from the example above). -->

<!-- ```{r} -->
<!-- renderPlot({powplo6()}, height = 650, width = 900) -->
<!-- ``` -->

<!-- ## Nitrogen analyses, all stations {.tabset .tabset-pills} -->

<!-- ```{r} -->
<!-- allnitdat <- medat %>% -->
<!--   filter(Parameter %in% c('AmmoniaN', 'NitrateNitriteNO3', 'TKN')) %>% -->
<!--   mutate( -->
<!--     Parameter = case_when( -->
<!--       Parameter %in% 'AmmoniaN' ~ 'Ammonia', -->
<!--       Parameter %in% 'NitrateNitriteNO3' ~ 'Nitrate, Nitrite', -->
<!--       Parameter %in% 'TKN' ~ 'Total Kjeldahl Nitrogen' -->
<!--     ), -->
<!--     Year = year(Date), -->
<!--     Month = month(Date, label = T) -->
<!--   ) %>% -->
<!--   group_by(StationCode, Parameter, Year) %>% -->
<!--   summarise( -->
<!--     Result = mean(Result, na.rm = T), -->
<!--   ) %>% -->
<!--   group_by(StationCode, Parameter) %>% -->
<!--   filter(n() == 10) %>% -->
<!--   mutate( -->
<!--     avg = mean(Result, na.rm = T), -->
<!--     dev = Result - avg -->
<!--   ) %>% -->
<!--   nest %>% -->
<!--   mutate( -->
<!--     res = purrr::map(data, function(x){ -->

<!--       knout <- kendallTrendTest(dev ~ Year, x) -->
<!--       outest <- round(knout$estimate, 2) -->
<!--       outpval <- p_ast(knout$p.value) -->
<!--       nval <- nrow(na.omit(x)) -->
<!--       out <- c(n = nval, outest, pval = outpval) %>% -->
<!--         data.frame %>% -->
<!--         t %>% -->
<!--         data.frame %>% -->
<!--         select(-intercept) -->
<!--       return(out) -->

<!--     }) -->

<!--   ) %>% -->
<!--   select(-data) %>% -->
<!--   unnest(res) %>% -->
<!--   mutate( -->
<!--     tau = as.numeric(as.character(tau)), -->
<!--     slope = as.numeric(as.character(slope)), -->
<!--     trend = ifelse(tau < 0, 'dec', 'inc') -->
<!--   ) -->
<!-- ``` -->

<!-- Kendall tests provide an indication of a trend by evaluating magnitude, direction, and significance of a change in density between the selected years. The test is a non-parametric equivalent to the regression analysis above. The value for tau ranges from -1 to 1 and provides a measure of trend direction. The slope is the estimated change per year in density and the p-value shows the significance of the test. -->

<!-- The maps show the value for tau (direction of trend) for a Kendall test of nitrogen changes for stations with ten years of data, green for decreasing and red for increasing. Size of the point is the magnitude of the estimated change between the three nitrogen constituents (ammonia left, nitrate/nitrite middle, total Kjeldahl nitrogen right).  The table shows the detailed results from the map. -->

<!-- ```{r} -->
<!-- locs <- medat %>% -->
<!--   select(StationCode, Longitude, Latitude) %>% -->
<!--   unique -->

<!-- tomap <- allnitdat %>% -->
<!--   left_join(locs, by = 'StationCode') %>% -->
<!--   st_as_sf(coords = c("Longitude", "Latitude"), crs = prj) -->

<!-- # point colors -->
<!-- cols <- tomap %>% -->
<!--   mutate( -->
<!--     cols = factor(trend, levels = c('dec', 'inc'), labels = c('lightgreen', 'tomato1')), -->
<!--     cols = as.character(cols) -->
<!--   ) %>% -->
<!--   pull(cols) -->

<!-- # size values -->
<!-- cexv <- tomap %>% -->
<!--   pull(tau) %>% -->
<!--   abs %>% -->
<!--   scales::rescale(to = c(2, 15)) -->

<!-- # hover pt labels -->
<!-- labs <- paste(tomap$StationCode, ': ', tomap$trend, ', tau = ', tomap$tau, ', p = ', tomap$pval) -->

<!-- mapviewOptions(leafletHeight = 400) -->

<!-- m1sel <- 'Ammonia' -->
<!-- m1map <- tomap %>% filter(Parameter %in% m1sel) -->
<!-- m1cexv <- cexv[tomap$Parameter %in% m1sel] -->
<!-- m1labs <- labs[tomap$Parameter %in% m1sel] -->
<!-- m1cols <- cols[tomap$Parameter %in% m1sel] -->
<!-- m1b <- mapview(m1map, zcol = 'tau', cex = m1cexv, label = m1labs, col.regions = m1cols, legend = F, layer.name = m1sel, map.types = mptyps) -->

<!-- m2sel <- 'Nitrate, Nitrite' -->
<!-- m2map <- tomap %>% filter(Parameter %in% m2sel) -->
<!-- m2cexv <- cexv[tomap$Parameter %in% m2sel] -->
<!-- m2labs <- labs[tomap$Parameter %in% m2sel] -->
<!-- m2cols <- cols[tomap$Parameter %in% m2sel] -->
<!-- m2b <- mapview(m2map, zcol = 'tau', cex = m2cexv, label = m2labs, col.regions = m2cols, legend = F, layer.name = m2sel, map.types = mptyps) -->

<!-- m3sel <- 'Total Kjeldahl Nitrogen' -->
<!-- m3map <- tomap %>% filter(Parameter %in% m3sel) -->
<!-- m3cexv <- cexv[tomap$Parameter %in% m3sel] -->
<!-- m3labs <- labs[tomap$Parameter %in% m3sel] -->
<!-- m3cols <- cols[tomap$Parameter %in% m3sel] -->
<!-- m3b <- mapview(m3map, zcol = 'tau', cex = m3cexv, label = m3labs, col.regions = m3cols, legend = F, layer.name = m3sel, map.types = mptyps) -->

<!-- leafsync::sync(m1b, m2b, m3b, ncol = 3) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- totab <- allnitdat %>% -->
<!--   ungroup %>% -->
<!--   arrange(Parameter, StationCode) %>% -->
<!--   mutate( -->
<!--     Parameter = ifelse(duplicated(Parameter), '', Parameter) -->
<!--   ) %>% -->
<!--   select(Parameter, StationCode, everything()) -->

<!-- HTML(knitr::kable(totab, format = 'html') %>% -->
<!--        kable_styling(full_width = T, font_size = 14)) -->
<!-- ``` -->