---
output: 
    html_document:
        code_folding: hide
---

# Evaluation of OC MS4 monitoring program, mass emissions {.tabset}

```{r setup, message = F, warning = F, results = 'hide'}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, fig.path = 'figs/', dev.args = list(family = 'serif'))

library(tidyverse)
library(sf)
library(mapview)
library(lubridate)
library(leafsync)
library(viridisLite)
library(lubridate)
library(patchwork)

mapviewOptions(leafletHeight = 300)

prj <- 4326 # wgs84

data(dwdat)
data(medat)
```

## Map summary

Watersheds monitored, number of parameters measured, and number of years monitored at each station. 

```{r}
tomap <- medat %>% 
  select(StationCode, Watershed, Longitude, Latitude) %>% 
  unique %>% 
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = prj)

m1 <- mapview(tomap, zcol = 'Watershed', layer.name = 'Watershed location', homebutton = F)

tomap <- medat %>% 
  select(StationCode, Parameter, Longitude, Latitude) %>% 
  unique %>% 
  group_by(StationCode, Longitude, Latitude) %>% 
  summarise(n = n()) %>% 
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = prj)

m2 <- mapview(tomap, zcol = 'n', layer.name = 'Number of parameters', homebutton = F, col.regions = magma)

tomap <- medat %>% 
  select(StationCode, yr = Date, Longitude, Latitude) %>% 
  mutate(yr = year(yr)) %>% 
  unique %>% 
  group_by(StationCode, Longitude, Latitude) %>% 
  summarise(n = n()) %>% 
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = prj)

m3 <- mapview(tomap, zcol = 'n', layer.name = 'Number of years', homebutton = F, col.regions = magma)

leafsync::sync(m1, m2, m3, ncol = 1) 
```

## Nitrogen analyses, SDMF05 {.tabset .tabset-pills}

### Observed

Observed time series for major nitrogen constituents.

```{r, fig.height = 5, fig.width = 6, out.width = '80%', fig.align = 'center'}
thm <- theme_bw() + 
  theme(
    strip.background = element_blank(), 
    strip.placement = 'outside', 
    axis.title = element_blank(), 
    legend.title = element_blank(), 
    legend.position = 'bottom', 
    panel.grid = element_blank()
  )
  
nitdat <- medat %>% 
  filter(StationCode %in% 'SDMF05') %>% 
  filter(Parameter %in% c('AmmoniaN', 'NitrateNitriteNO3', 'TKN')) %>% 
  mutate(
    Parameter = case_when(
      Parameter %in% 'AmmoniaN' ~ 'Ammonia', 
      Parameter %in% 'NitrateNitriteNO3' ~ 'Nitrate, Nitrite', 
      Parameter %in% 'TKN' ~ 'Total Kjeldahl Nitrogen'
    ), 
    Detection = case_when(
      Qualifier %in% '<' ~ 'below detection', 
      T ~ 'within range'
    ),
    Year = year(Date), 
    Month = month(Date, label = T)
  )

toplo <- nitdat

p1 <- ggplot(toplo, aes(x = Date, y = Result)) + 
  geom_line() + 
  geom_point(aes(colour = Detection)) + 
  facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
  thm + 
  # scale_y_log10() + 
  scale_colour_manual(values = c('tomato1', 'black')) + 
  labs(
    title = 'Observed nitrogen (mg/L)', 
    subtitle = 'SDMF05'
  )

p2 <- ggplot(toplo, aes(x = factor(Year), y = Result, group = Year)) + 
  geom_boxplot() + 
  facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
  thm +
  # scale_y_log10() + 
  # scale_colour_manual(values = c('tomato1', 'black')) + 
  labs(
    title = 'Observed nitrogen (mg/L) by year', 
    subtitle = 'SDMF05'
  )

p3 <- ggplot(toplo, aes(x = Month, y = Result, group = Month)) + 
  geom_boxplot() + 
  facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
  thm +
  # scale_y_log10() + 
  # scale_colour_manual(values = c('tomato1', 'black')) + 
  labs(
    title = 'Observed nitrogen (mg/L) by month', 
    subtitle = 'SDMF05'
  )

p1
p2 
p3
```

### Trends

```{r, fig.height = 5, fig.width = 6, out.width = '80%', fig.align = 'center'}
thm <- theme_bw() + 
  theme(
    strip.background = element_blank(), 
    strip.placement = 'outside', 
    axis.title = element_blank(), 
    legend.title = element_blank(), 
    legend.position = 'bottom', 
    panel.grid = element_blank()
  )

toplo <- nitdat %>% 
  group_by(Parameter, Year) %>% 
  summarise(
    confint = t.test(Result)$conf.int %>% range %>% diff,
    confint = confint / 2, 
    Result = mean(Result, na.rm = T), 
  ) %>% 
  group_by(Parameter) %>% 
  mutate(
    avg = mean(Result, na.rm = T),
    dev = Result - avg
  )

p1 <- ggplot(toplo, aes(x = Year, y = dev, fill = dev)) + 
  geom_bar(stat = 'identity', colour = 'grey') + 
  # geom_errorbar(aes(ymin = dev - confint, ymax = dev + confint), width = 0) +
  scale_fill_gradient2('', low = 'tomato1', mid = 'white', high = 'lightgreen', midpoint = 0) +
  facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
  thm +
  geom_smooth(method = 'lm', se = F, linetype = 'dashed', color = 'black') + 
  # scale_y_log10() + 
  # scale_y_continuous('Density (fish/100ft)') +
  geom_hline(aes(yintercept = 0)) + 
  labs(
    title = 'Deviation from annual averages by constuent (mg/L)', 
    subtitle = 'SDMF05'
  )

p1

win <- 12
toplo <- nitdat %>%
  select(Date, Parameter, Result) %>%
  mutate(Date = floor_date(Date, unit = 'month')) %>% 
  group_by(Date, Parameter) %>% 
  summarise(Result = mean(Result, na.rm = T)) %>% 
  # group_by(Parameter) %>% 
  arrange(Parameter, Date) %>% 
  group_by(Parameter) %>% 
  mutate(
    avg = stats::filter(Result, rep(1, win)/win, sides = 1, method = 'convolution')
  ) %>% 
  ungroup %>% 
  mutate(
    dev = Result - avg
  )

p1 <- ggplot(toplo, aes(x = Date, y = Result)) + 
  geom_line() + 
  facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
  thm + 
  # scale_y_log10() + 
  scale_colour_manual(values = c('tomato1', 'black')) + 
  labs(
    title = 'Observed nitrogen (mg/L)', 
    subtitle = 'SDMF05'
  )

p2 <- ggplot(toplo, aes(x = Date, y = avg)) + 
  geom_line() + 
  geom_segment(aes(x = Date, xend = Date, yend = avg, y = avg + dev)) + 
  facet_wrap(~Parameter, strip.position = 'left', ncol = 1, scales = 'free_y') +
  thm + 
  # scale_y_log10() + 
  scale_colour_manual(values = c('tomato1', 'black')) + 
  labs(
    title = 'Observed nitrogen (mg/L), deviations from annual average', 
    subtitle = 'SDMF05'
  )

p1
p2
```
